name: planning-data-specialist
dependencies:
  - python = 3.8*
packages:
  - pandas
  - openpyxl
  - sqlalchemy
  - python-dotenv
  - matplotlib
  - seaborn
channels:
  -conda-forge
  - default
  - pip
